# Final Exam Full mark is 100  พิมพ์ตอบในipynbนี้

# 1. นายกอต้องการ sort ค่าตัวเลขในลิสต์  นายกอทำแบบนี้

In [4]:
k = ['1','923','23','8345']
sorted(k)

['1', '23', '8345', '923']

# นายกอสงสัยว่า เขาควรจะได้ [1, 23, 923, 8345]  ทำไมนายกอถึงไม่ได้ดังที่ต้องการ   จงอธิบาย  

# จงแก้โค้ดแก้ไขตามความต้องการของนายกอ

# 2. นายขอเขียน [print(k) for k in range(5)]  หลังจากลองรันดู มี
[None, None, None, None, None]  เป็นผลลัพธ์   ถามว่าเกิดจากเหตุใด  จงอธิบาย


In [8]:
[print(k) for k in range(5)]

0
1
2
3
4


[None, None, None, None, None]

# นายขอ ต้องการพิมพ์ด้านบนอย่างเดียว ไม่ต้องการลิสต์ [None, None, None, None, None] จงแก้โค้ดแก้ไขตามความต้องการของนายขอ

# 3. นายคอคาดว่า x จะไม่นิยามใน foo() จึงเตรียม exception เอาไว้  แต่ปรากฏว่าพิมพ์10  เพราะอะไร โปรดอธิบาย

In [5]:
x = 10
def foo():
    try:
        print(x)
    except NameError:
        print('Name Error')
        

In [26]:
foo()

10


# 4. จากข้อสาม  นายคอเลยทำแบบนี้  แต่กลับได้ UnboundLocalError เพราะอะไร

In [7]:
x = 10
def foo():
    x += 1
    print(x)

In [8]:
foo()

UnboundLocalError: local variable 'x' referenced before assignment

# 5. จงแก้ไขโค้ดข้อ4 ให้พิมพ์ 11  โดยใช้ global, nonlocal. ใส่ตรงคำว่า#Your code here

In [11]:
x = 10
def foo():
    global x
    x += 1
    print(x)

In [12]:
foo()

11


# 6. ทำไม lst ในfoo1ถึงถูก append , แต่ lst ใน foo2เกิด error?

In [43]:
lst = [1, 2, 3]
def foo1():
    lst.append(5)   # This works ok

foo1()
print(lst)


[1, 2, 3, 5]


In [44]:
def foo2():
    lst += [5]   
    
foo2()

UnboundLocalError: local variable 'lst' referenced before assignment

# 7 ทำไมค่า b เปลี่ยน  เมื่อเราเปลี่ยนค่า a[1][1] ?

In [49]:
a=[1,[2,3],4]
b=a[1]


In [50]:
b

[2, 3]

In [51]:
a[1][1] =100

In [52]:
b

[2, 100]

# 8. นักเรียนคิดว่าข้อนี้ ผู้เขียนโปรแกรมทำอะไรผิดจึงเกิด IndexError?

In [54]:
odd = lambda x : bool(x % 2)
numbers = [n for n in range(10)]
for i in range(len(numbers)):
    if odd(numbers[i]):
        del numbers[i]  

IndexError: list index out of range

# 9. จงแก้ไขให้ b ไม่เปลี่ยนตาม a

In [55]:
import numpy as np
a =np.array([[2,3,4],[1,4,5]])
b = a
a[0][0]=100
print(a)
print(b)

[[100   3   4]
 [  1   4   5]]
[[100   3   4]
 [  1   4   5]]


# จะสังเกตุว่าเมื่อเราเปลี่ยนa[0][0], เราทำให้ b[0][0] เปลี่ยนตาม  จงแก้ไขให้มันไม่เปลี่ยนตาม

[[100   3   4]
 [  1   4   5]]
[[2 3 4]
 [1 4 5]]


# 10. โค้ดด้านล่างผิดตรงไหน? ทำไมเกิด type error

In [1]:
class A:
    def __init__():
        pass
    
    def amethod():
        pass
        

In [2]:
anA = A()
anA.amethod()

TypeError: __init__() takes 0 positional arguments but 1 was given

# 11. จงอธิบายว่า with ในการทำงานกับไฟล์

In [79]:
with open("test.txt",'w',encoding = 'utf-8') as f:
    f.write("This file ------\n\n")
    f.write("11 22\n\n")

# ต่างกับ

In [80]:
f2 = open('test.txt','w')
f2.write("This file ------\n\n")
f2.write("11 22\n\n")

7

# อย่างไร?

# 12. ทำไมหลังบรรทัด del p.x , ค่าของ p.xยังอยู่และมีค่าเท่ากับ10?

In [83]:
class TV:
    x = 10
    y = 7
    
p = TV()
print('p.x',p.x) 
print('p.y',p.y)  
p.x = 12 
print('p.x',p.x) 
del p.x 
print('p.x aftr del',p.x) 

p.x 10
p.y 7
p.x 12
p.x aftr del 10


# 13. Code นี้ผิดอย่างไร

In [84]:
t = (1,2,3)
t[1] = 9

TypeError: 'tuple' object does not support item assignment

# 14. ทำไม y ถึงเปลี่ยนค่าตาม x ด้วย

In [86]:
y = [1,2,3]

def func(x):
    x.append(4)
    x[0] = -100

func(y)

print(y)

[-100, 2, 3, 4]


# จงแก้ไขโค้ดให้ y ไม่เปลี่ยนตาม x

# 15. ทำไมถึงเกิด error

In [87]:
def kwo(*a, c):
    print(a, c)

kwo(1, 2) 

TypeError: kwo() missing 1 required keyword-only argument: 'c'

# จงแก้ไข เรียกฟังก์ชั่นนี้ไม่ให้เกิด error 

# 16. นายบีต้องการสร้างaให้มีค่าเริ่มต้น listว่าง แต่ไม่ได้ต้องการให้เกิดปัญหาที่พอเรียกครั้งที่สอง a ไม่ใช่ลิสต์ว่างแล้วเพิ่มelementจากการเรียกครั้งแรกอีกด้วย  ปัญหานี้จะแก้ไขอย่างไร

In [3]:
def func(b,a=[]):
    print(a)
    print(b)
    print('#' * 12)
    a.append(b) 

func(1)
func(2)
func(3)

'''
ไม่ได้ต้องการแบบนี้  แบบที่เพิ่มelementจากการเรียกครั้งที่แล้ว
############
[1]
2
############
[1, 2]
3
############
'''

[]
1
############
[1]
2
############
[1, 2]
3
############


# 17. จงเขียนโค้ดให้ 
cnp=[[ 2  6 10],
 [ 3  7 11]]
 โดยการบวกระหว่างanpกับbnpแบบbroadcasting 
 # ตรง  Your code here

In [91]:
anp = np.array([[1 ,2],[3,4],[5,6]])
bnp = np.array([1,3,5])
cnp = #Your code here
print(cnp)

[[ 2  6 10]
 [ 3  7 11]]


# 18. นายกอต้องการ nested list โดยมีลิสต์ข้างในเหมือนกันสี่ชุดจึงสร้างลิสต์ดังนี้

In [94]:
x = [[1,2,3]]*4
print(x)

[[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]]


# ถ้านายกอต้องการเปลี่ยน x[1][1] แค่ค่าเดียว จะเกิดบั๊คอะไรขึ้น?  

[[1, 100, 3], [1, 100, 3], [1, 100, 3], [1, 100, 3]]


# นายกอควรแก้ไขโดยการสร้างลิสต์ใหม่อย่างไร?

# 19. จงเรียงลำดับลิสต์ของทูเปิลจากมากไปน้อย  โดยการนำค่าที่มากที่สุดในtupeมาเป็นตัววัดว่า tupeใดมากกว่า เช่น
(2,3) vs (0,5) vs (1,2) <br>
max(2,3) =3<br>
max (0,5) = 5<br>
เพราะฉะนั้น (0,5) > (2,3)<br>


# บอกใบ้: ใช้ sorted โดยมี key เป็น lambda function ที่คำนวน max ของ tuple

a = [(2,3),(5,9),(-2,4),(0,8)] <br>
หลังเรียง ได้คำตอบ asort = [(5, 9), (0, 8), (-2, 4), (2, 3)]

In [5]:
a = [(2,3),(9,5),(4,-2),(0,8)]
asort = sorted(#Your Code Here
print(asort)

[(9, 5), (0, 8), (4, -2), (2, 3)]


# 20 จงเรียงลำดับลิสต์ของObjectจากมากไปน้อย  โดยการนำค่าที่มากที่สุดในObjectมาเป็นตัววัดว่า Object ใดมากกว่า เช่น
Object1(2,3) vs Object1(0,5) vs Object1(1,2) <br>
max(2,3) =3<br>
max (0,5) = 5<br>
เพราะฉะนั้น Object1(0,5) > Object1(2,3)<br>


# บอกใบ้: Define __gt__ แล้วใช้sorted โดยไม่ต้องใช้key

In [6]:
class Object1:
    def __init__(self,a):
        self.a = a[0]
        self.b = a[1]
        
    def __str__(self):
        return f"Object1({self.a},{self.b})"
        
    def __gt__(self,other):
        return #Your Code Here

In [7]:
a = [(2,3),(9,5),(4,-2),(0,8)]
aObj1s = [Object1(i) for i in a]
for i in aObj1s:
    print(i)

Object1(2,3)
Object1(9,5)
Object1(4,-2)
Object1(0,8)


In [8]:
aObj1sSorted = sorted(#Your Code Here

In [9]:
for i in aObj1sSorted:
    print(i)

Object1(9,5)
Object1(0,8)
Object1(4,-2)
Object1(2,3)
