# Final Exam Full mark is 100  พิมพ์ตอบในipynbนี้

# 1. นายกอต้องการ sort ค่าตัวเลขในลิสต์  นายกอทำแบบนี้

In [15]:
k = ['1','923','23','8345']
sorted(k)

['1', '23', '8345', '923']

# นายกอสงสัยว่า เขาควรจะได้ [1, 23, 923, 8345]  ทำไมนายกอถึงไม่ได้ดังที่ต้องการ   จงอธิบาย  

In [7]:
เพราะว่าค่าที่อยู่ในลิสต์ เป็น str sorted จะค่าตามลำดับเลข ASCII

['1', '23', '7000', '923']


# จงแก้โค้ดแก้ไขตามความต้องการของนายกอ

In [22]:
k=[int(i) for i in k]
print(sorted(k))


[1, 23, 923, 8345]


# 2. นายขอเขียน [print(k) for k in range(5)]  หลังจากลองรันดู มี
[None, None, None, None, None]  เป็นผลลัพธ์   ถามว่าเกิดจากเหตุใด  จงอธิบาย


In [37]:
[print(k) for k in range(5)]

0
1
2
3
4


[None, None, None, None, None]

เพราะว่าใส่คำสั่ง print ลงไปใน list comprehension จึงทำให้มีค่า None ออกมา

# นายขอ ต้องการพิมพ์ด้านบนอย่างเดียว ไม่ต้องการลิสต์ [None, None, None, None, None] จงแก้โค้ดแก้ไขตามความต้องการของนายขอ

In [36]:
for i in [k for k in range(5)]:
    print(i)

0
1
2
3
4


# 3. นายคอคาดว่า x จะไม่นิยามใน foo() จึงเตรียม exception เอาไว้  แต่ปรากฏว่าพิมพ์10  เพราะอะไร โปรดอธิบาย

In [205]:
x = 10
def foo():
    try:
        print(x)
    except NameError:
        print('Name Error')
        

In [206]:
foo()

10


# 4. จากข้อสาม  นายคอเลยทำแบบนี้  แต่กลับได้ UnboundLocalError เพราะอะไร

In [58]:
x = 10
def foo():
    x += 1
    print(x)

In [60]:
foo()

UnboundLocalError: cannot access local variable 'x' where it is not associated with a value

เพราะว่า x ไม่ได้ถูกประกาศใน foo() แต่เรียกใช้ใน foo() จึงทำให้เกิด UnboundLocalError

# 5. จงแก้ไขโค้ดข้อ4 ให้พิมพ์ 11  โดยใช้ global, nonlocal. ใส่ตรงคำว่า#Your code here

In [171]:
x = 10
def foo(x):
    # Your code here
    x += 1
    print(x)

In [172]:
foo(x)

11


# 6. ทำไม lst ในfoo1ถึงถูก append , แต่ lst ใน foo2เกิด error?

In [61]:
lst = [1, 2, 3]
def foo1():
    lst.append(5)   # This works ok

foo1()
print(lst)


[1, 2, 3, 5]


In [62]:
def foo2():
    lst += [5]   
    
foo2()

UnboundLocalError: cannot access local variable 'lst' where it is not associated with a value

เพราะว่า lst ใน foo1 ถูกประกาศใน foo1() แต่ lst ใน foo2 ไม่ได้ถูกประกาศใน foo2() จึงทำให้เกิด error

# 7 ทำไมค่า b เปลี่ยน  เมื่อเราเปลี่ยนค่า a[1][1] ?

In [1]:
a=[1,[2,3],4]
b=a[1]


In [2]:
b

[2, 3]

In [3]:
a[1][1] =100

In [4]:
b

[2, 100]

เพราะว่า a และ b มีค่าเป็น list ซึ่งเป็น mutable จึงทำให้เกิดการเปลี่ยนแปลงค่า

# 8. นักเรียนคิดว่าข้อนี้ ผู้เขียนโปรแกรมทำอะไรผิดจึงเกิด IndexError?

In [173]:
odd = lambda x : bool(x % 2)
numbers = [n for n in range(10)]
for i in range(len(numbers)):
    if odd(numbers[i]):
        del numbers[i]  

IndexError: list index out of range

ผิดตรงที่เข้าถึง index ที่ไม่มีอยู่จริง

# 9. จงแก้ไขให้ b ไม่เปลี่ยนตาม a

In [23]:
import numpy as np
a =np.array([[2,3,4],[1,4,5]])
b =np.array(a)
a[0][0]=100
print(a)
print(b)

[[100   3   4]
 [  1   4   5]]
[[2 3 4]
 [1 4 5]]


In [19]:
pip list

Package                  Version
------------------------ -----------
anyio                    3.6.2
appnope                  0.1.3
argon2-cffi              21.3.0
argon2-cffi-bindings     21.2.0
arrow                    1.2.3
asttokens                2.2.1
attrs                    22.1.0
backcall                 0.2.0
beautifulsoup4           4.11.1
bleach                   5.0.1
cffi                     1.15.1
comm                     0.1.2
debugpy                  1.6.4
decorator                5.1.1
defusedxml               0.7.1
entrypoints              0.4
executing                1.2.0
fastjsonschema           2.16.2
fqdn                     1.5.1
idna                     3.4
iniconfig                1.1.1
ipykernel                6.19.2
ipython                  8.7.0
ipython-genutils         0.2.0
ipywidgets               8.0.3
isoduration              20.11.0
jedi                     0.18.2
Jinja2                   3.1.2
jsonpointer              2.3
jsonschema               4.

# จะสังเกตุว่าเมื่อเราเปลี่ยนa[0][0], เราทำให้ b[0][0] เปลี่ยนตาม  จงแก้ไขให้มันไม่เปลี่ยนตาม

In [24]:
import numpy as np
a =np.array([[2,3,4],[1,4,5]])
b = np.array(a)
a[0][0]=100
print(a)
print(b)

[[100   3   4]
 [  1   4   5]]
[[2 3 4]
 [1 4 5]]


# 10. โค้ดด้านล่างผิดตรงไหน? ทำไมเกิด type error

In [185]:
class A:
    def __init__():
        pass
    
    def amethod():
        pass
        

In [186]:
anA = A()
anA.amethod()

TypeError: A.__init__() takes 0 positional arguments but 1 was given

In [187]:
เพราะว่า ใน class ไม่มีการสร้าง method ที่ชื่อว่า amethod แต่มีการสร้าง method ที่ชื่อว่า __init__ ซึ่งเป็น method ที่ทำงานเมื่อสร้าง object ขึ้นมา

SyntaxError: invalid syntax (2831983794.py, line 1)

# 11. จงอธิบายว่า with ในการทำงานกับไฟล์

In [75]:
with open("test.txt",'w',encoding = 'utf-8') as f:
    f.write("This file ------\n\n")
    f.write("11 22\n\n")

# ต่างกับ

In [76]:
f2 = open('test.txt','w')
f2.write("This file ------\n\n")
f2.write("11 22\n\n")

7

# อย่างไร?

# 12. ทำไมหลังบรรทัด del p.x , ค่าของ p.xยังอยู่และมีค่าเท่ากับ10?

In [83]:
class TV:
    x = 10
    y = 7
    
p = TV()
print('p.x',p.x) 
print('p.y',p.y)  
p.x = 12 
print('p.x',p.x) 
del p.x 
print('p.x aftr del',p.x) 

p.x 10
p.y 7
p.x 12
p.x aftr del 10


เพราะว่า p.x ไม่ได้อยู่ class TV x จึงกลับไปเป็นค่าเดิม

# 13. Code นี้ผิดอย่างไร

In [208]:
t = (1,2,3)
t[1] = 9
print(t)

TypeError: 'tuple' object does not support item assignment

เพราะว่า tuple  ไม่ได้เป็นค่าที่สามารถเปลี่ยนแปลงได้

# 14. ทำไม y ถึงเปลี่ยนค่าตาม x ด้วย

In [214]:
y = [1,2,3]

def func(x):
    x.append(4)
    x[0] = -100

func(y)

print(y)

[-100, 2, 3, 4]


เพราะว่า x และ y อ้างอิงถึงค่าเดียวกัน

# จงแก้ไขโค้ดให้ y ไม่เปลี่ยนตาม x

In [216]:
def func(x):
    x = 100

[-100, 2, 3, 4]


# 15. ทำไมถึงเกิด error

In [218]:
def kwo(*a, c):
    print(a, c)

kwo(1, 2) 

TypeError: kwo() missing 1 required keyword-only argument: 'c'

เพราะว่า a ต้องรับค่าเป็น int แต่เราใส่

# จงแก้ไข เรียกฟังก์ชั่นนี้ไม่ให้เกิด error 

In [217]:
kwo(1, 2, c=3)

(1, 2) 3


# 16. นายบีต้องการสร้างaให้มีค่าเริ่มต้น listว่าง แต่ไม่ได้ต้องการให้เกิดปัญหาที่พอเรียกครั้งที่สอง a ไม่ใช่ลิสต์ว่างแล้วเพิ่มelementจากการเรียกครั้งแรกอีกด้วย  ปัญหานี้จะแก้ไขอย่างไร

In [168]:
def func(b,a=[]):
    print(a)
    print(b)
    print('#' * 12)
    a.append(b) 

func(1)
func(2)
func(3)

'''
ไม่ได้ต้องการแบบนี้  แบบที่เพิ่มelementจากการเรียกครั้งที่แล้ว
############
[1]
2
############
[1, 2]
3
############
'''

[]
1
############
[1]
2
############
[1, 2]
3
############


'\nไม่ได้ต้องการแบบนี้  แบบที่เพิ่มelementจากการเรียกครั้งที่แล้ว\n############\n[1]\n2\n############\n[1, 2]\n3\n############\n'

# 17. จงเขียนโค้ดให้ 
cnp=[[ 2  6 10],
 [ 3  7 11]]
 โดยการบวกระหว่างanpกับbnpแบบbroadcasting 
 # ตรง  Your code here

In [202]:
import numpy as np

anp = np.array([[1 ,2],[3,4],[5,6]])
bnp = np.array([1,3,5])
cnp = np.array(anp+bnp)
print(cnp)

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

# 18. นายกอต้องการ nested list โดยมีลิสต์ข้างในเหมือนกันสี่ชุดจึงสร้างลิสต์ดังนี้

In [220]:
x = [[1,2,3]]*4
print(x)

[[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]]


# ถ้านายกอต้องการเปลี่ยน x[1][1] แค่ค่าเดียว จะเกิดบั๊คอะไรขึ้น?  

In [221]:
print(x[1][1])

2


# นายกอควรแก้ไขโดยการสร้างลิสต์ใหม่อย่างไร?

In [183]:
k =[i for i in x]
print(k)

[[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]]


# 19. จงเรียงลำดับลิสต์ของทูเปิลจากมากไปน้อย  โดยการนำค่าที่มากที่สุดในtupeมาเป็นตัววัดว่า tupeใดมากกว่า เช่น
(2,3) vs (0,5) vs (1,2) <br>
max(2,3) =3<br>
max (0,5) = 5<br>
เพราะฉะนั้น (0,5) > (2,3)<br>


# บอกใบ้: ใช้ sorted โดยมี key เป็น lambda function ที่คำนวน max ของ tuple

a = [(2,3),(5,9),(-2,4),(0,8)] <br>
หลังเรียง ได้คำตอบ asort = [(5, 9), (0, 8), (-2, 4), (2, 3)]

In [281]:
a = [(2,3),(9,5),(4,-2),(0,8)]
asort = [ i for i in zip(reversed(sorted(a)))]
print(asort)

[((9, 5), (2, 3)), ((4, -2), (9, 5)), ((2, 3), (4, -2)), ((0, 8), (0, 8))]


# 20 จงเรียงลำดับลิสต์ของObjectจากมากไปน้อย  โดยการนำค่าที่มากที่สุดในObjectมาเป็นตัววัดว่า Object ใดมากกว่า เช่น
Object1(2,3) vs Object1(0,5) vs Object1(1,2) <br>
max(2,3) =3<br>
max (0,5) = 5<br>
เพราะฉะนั้น Object1(0,5) > Object1(2,3)<br>


# บอกใบ้: Define __gt__ แล้วใช้sorted โดยไม่ต้องใช้key

In [203]:
class Object1:
    def __init__(self,a):
        self.a = a[0]
        self.b = a[1]
        
    def __str__(self):
        return f"Object1({self.a},{self.b})"
        
    def __gt__(self,other):
        return self.a > other.a

In [120]:
a = [(2,3),(9,5),(4,-2),(0,8)]
aObj1s = [Object1(i) for i in a]
for i in aObj1s:
    print(i)

Object1(2,3)
Object1(9,5)
Object1(4,-2)
Object1(0,8)


In [223]:
aObj1sSorted = reversed(sorted(aObj1s))

In [224]:
for i in aObj1sSorted:
    print(i)

Object1(9,5)
Object1(4,-2)
Object1(2,3)
Object1(0,8)
